### ISSUE TITLE
SpaceMonkey silently goes away when I start my SteamVR progrm VTOL VR or Warplanes WW1

### ISSUE THREAD

**Issue by rickrsr** [PHARTGAMES/SpaceMonkey#18]
Hi -
Through yesterday, May 14 2021, SpaceMonkey was working fine for me.
But, today, May 15 2021, when I launched either VTOL VR or Warplanes WW1 in SteamVR, SpaceMonkey silently went away, with no messages or Windows 10 Event Log entries.

Also, I am using Sim Racing Studio, and when SpaceMonkey went away, the Sim Racing Studio Profile in use changed from SpaceMonkey to Stand By.

When I ran Warplanes WW1 in Steam Desktop, SpaceMonkey did not go away.
Finally, I lauched BeamNG in Steam desktop, and SpaceMonkey did not go away.

Thanks for any help you could give me with this problem.

Regards -
Rick Rothstein

**Comment by rickrsr** [comment]
Here is what works for me to get around the problem.  When I'm finished playing a SpaceMonkey game, just X out of all SpaceMonkey. Then in Windows Task Manager, just kill any SpaceMonkeyTeleprocessingProvider App or Background Process that is still hanging around.

**Comment by PHARTGAMES** [comment]
Thanks for letting me know.

This is a known issue that has been fixed in the repo but hasn't made it
into a release just yet and you have the right work around.

cheers.
