### ISSUE TITLE
Does not interface properly with Simhub

### ISSUE THREAD

**Issue by M0nk3yofdoom** [PHARTGAMES/SpaceMonkey#31]
Works a little bit with Wreckfest connecting to simhub via their dirt3 or dirt2 game telemetry but is not correctly formatted. Simhub does not recognise the data from Dakar Desert Rally. May need modification or a tutorial on how to make it work with Simhub - the free telemetry platform.

**Comment by PHARTGAMES** [comment]
This is fixed for release 1.0.7.

In 1.0.6 SpaceMonkey only supports 1 output format, in 1.0.7 you will be able to output to multiple formats, the main reason for that is to support SimHub :).

**Comment by M0nk3yofdoom** [comment]
awesome! Thank you for your hard work! testing it out now.
