### ISSUE TITLE
Is spacemonkey support for STAR WARS: Squadrons going to be fixed?

### ISSUE THREAD

**Issue by rickrsr** [PHARTGAMES/SpaceMonkey#33]
Github notes state that spacemonkey support for STAR WARS: Squadrons is currently broken:
"STAR WARS: Squadrons (Note: broken; requires pointer change)".
Are there plans to fix this problem?
Regards -

**Comment by rickrsr** [comment]
Thanks for the info. Right now I'm just using joystick physics, and it will
be interesting to see what sort of physics you've been able to extract.

**Comment by DigitalHyper** [comment]
I realize you have been busy.. but I just wanted to chime in and say that I look forward to the fix for Squadrons as well.  Really would like to have real telemetry instead of joystick.  Thanks for all you do.

**Comment by tobydz** [comment]
Hey Phart, if you have a moment, can you email me docs or links or anything that will ramp me up on the process for updating that pointer?  I've been a dev since the 90s, Assembly is one of my languages, and most relevant to this, testing the memory manager was one of the things I did as one of the original XBox creators. If you can get me some starting knowledge, I'll at least be able to update that pointer.... possibly more  (automatic identification of changes?). Feel free to reach me at tobydz @ gmail.  Cheers!

**Comment by DigitalHyper** [comment]
@tobydz .. that would be awesome. Hopefully they are still looking at the github. I have been wanting to play this game with Telemetry for some time now. I appreciate you chiming in and hopefully they will get back to you.

**Comment by rickrsr** [comment]
Same for me. It would be great to get the telemetry fixed.

**Comment by PHARTGAMES** [comment]
Cool, seems to be a fair bit of interest, I will update squadrons asap. Good excuse to try it with the new video card and WibbleWobble anyway :)

**Comment by PHARTGAMES** [comment]
Heey, so good news is that it still works as expected, no issues here with v1.1.1

For my test I had to re-download the game.

Then I just followed the instructions here
https://github.com/PHARTGAMES/SpaceMonkey#star-wars-squadrons

Perhaps the only thing I did differently to the instructions is I waited until I was in the game before I hit Initialize.

In the game meaning; I had loaded up my practice session, floating in space.

Please let me know if you figure it out, maybe the steps need changing.

@rickrsr @DigitalHyper @tobydz

**Comment by DigitalHyper** [comment]
@PHARTGAMES , I will try to test that soon and report back.

**Comment by DigitalHyper** [comment]
I tested, that seems to work. What do you play on? I have the DOF reality H6. Wondering if anyone has a profile for it. Gets nuts at times.. but I'm getting use to it. Meant to ask, does it make a difference if it's launched within Steam VR vs going to the folder? I would like to launch right into VR without having to go in and toggle it on within game.

**Comment by PHARTGAMES** [comment]
> I tested, that seems to work. What do you play on? I have the DOF reality H6. Wondering if anyone has a profile for it. Gets nuts at times.. but I'm getting use to it. Meant to ask, does it make a difference if it's launched within Steam VR vs going to the folder? I would like to launch right into VR without having to go in and toggle it on within game.

Does it make a difference if launched from inside steamvr; sorry no idea. I can't remember 100% but I think there's issues if you run it with the launcher exe and not the starwarssquadrons.exe.. I think the launcher checks easy anti cheat..? I don't know what steam does, I guess it uses the launcher or there wouldn't be an explicit step to run the starwarssquadrons.exe.

**Comment by tobydz** [comment]
> Heey, so good news is that it still works as expected, no issues here with v1.1.1
> 
> For my test I had to re-download the game.
> 
> Then I just followed the instructions here https://github.com/PHARTGAMES/SpaceMonkey#star-wars-squadrons
> 
> Perhaps the only thing I did differently to the instructions is I waited until I was in the game before I hit Initialize.
> 
> In the game meaning; I had loaded up my practice session, floating in space.
> 
> Please let me know if you figure it out, maybe the steps need changing.
> 
> @rickrsr @DigitalHyper @tobydz

You friggin rock @PHARTGAMES ….. seriously if it weren’t for you I’d have an astronomically expensive paperweight. Cheers brother!
