### ISSUE TITLE
Mechwarrior Plugin Pitch and Roll reversed

### ISSUE THREAD

**Issue by Alkman222** [PHARTGAMES/SpaceMonkey#34]
Hi, first thanks for this amazing software.
I have an issue with the Mw5 Plugin, Pitch and Roll are reversed, when i am look up, my rig roll right. how to reverse that ? I am using a Thanos Controlled sfx100 with Simracing Studio.

**Comment by PHARTGAMES** [comment]
Thanks, will check it out.

**Comment by PHARTGAMES** [comment]
> Hello, I have the same phenomenon with wreckfest experimental plugin. Traction loss is reversed ! My rig is Prosimu T1000 3DOF. Thanks

Hi it's probably unrelated to this specific issue. The experimental plugin is not being developed, try the non experimental version, it's much newer.

**Comment by PHARTGAMES** [comment]
This should be fixed in v1.0.7

**Comment by RaouleDuke77** [comment]
Hi,
Now, with the non experimental version, i have pitch and roll reversed but traction loss seems good! (v1.0.7)

**Comment by RaouleDuke77** [comment]
It is opposite now : pitch/roll are not good anymore with non experimental, it is reversed and traction loss is good!
