### ISSUE TITLE
Discord??

### ISSUE THREAD

**Issue by SerialMascot** [PHARTGAMES/SpaceMonkey#35]
@PHARTGAMES Looks like your discord invite expired :-(

Would love to have you involved in the effort to add telemetry to the FreeSpaceOpen Engine. Native VR is now in open Beta, and built-in-motion telemetry output has been long requested. I'm pretty good w/the physics model, and it's a very actively maintained open source game, so the sky's the limit on output variables. 

also: long time mech-nerd and I have some burning questions about your MW5 support

please visit https://www.youtube.com/@serialmascot396/about for more info, or come say hello in the development discord https://discord.gg/3ZpU7UgHJK

**Comment by PHARTGAMES** [comment]
https://discord.gg/DWBJGsNRT

**Comment by rado79** [comment]
Is it possible to get a new discord invite link?

**Comment by McFredward** [comment]
Both discord links are dead. Really would like to join a community around that project but I cannot find it anywhere. Would appreciate if you re-post a (permanent) discord link in here :)

**Comment by PHARTGAMES** [comment]
Have made a new discord link that wont expire

https://discord.gg/gGUufTdpgG
