### ISSUE TITLE
dakar desert rally no telemetry

### ISSUE THREAD

**Issue by Siethof** [PHARTGAMES/SpaceMonkey#37]
first thankx solving defaut config problem yesterday so quick! ok now

try to run dakar desert rally with sim racing studio . no result.
spacemonkey run as admin.
modfiles added in dakar desert map
unrealenginemodlaucher launced
no data in open motion ui
attached pics from spacemonkey an unrealengine.
maybe you can see whats wrong??

![sm6](https://github.com/PHARTGAMES/SpaceMonkey/assets/148687193/7d5257b4-4843-4ccb-9ce8-79a713ccaacf)
![sm1](https://github.com/PHARTGAMES/SpaceMonkey/assets/148687193/99206106-c3b6-4d03-8034-2252043178b0)
![sm2](https://github.com/PHARTGAMES/SpaceMonkey/assets/148687193/56bfc3bf-f373-4c29-820b-21e343566347)
![sm3](https://github.com/PHARTGAMES/SpaceMonkey/assets/148687193/5e21d25e-b85a-4648-aca2-309dfef86f29)
![sm4](https://github.com/PHARTGAMES/SpaceMonkey/assets/148687193/a86a46ed-8ac4-4712-82a8-1fc2c1da9179)
![sm5](https://github.com/PHARTGAMES/SpaceMonkey/assets/148687193/b7a6532f-234d-4b3a-9f4e-dfca7e1e6a5a)

**Comment by PHARTGAMES** [comment]
The instruction for copying is

"Extract the contents of Dakar2Mod_0.2.zip into where you installed your Dakar Desert Rally game."

so the contents are these two folders

![image](https://github.com/PHARTGAMES/SpaceMonkey/assets/13314042/95461004-deaa-487f-9fed-bce7c7828190)

I think your extraction program decided to put it into another folder for you :)
Everything else looks right though, cheers

**Comment by Siethof** [comment]
i put it in folder : steam, steamapps , common , dakar desert rally  and left it in the  dakar2mod folder (see pic)
and also put it   in  the dakar2game folder  , in dakar desert folder 
took it out of the  dakar2mod folder as  2  files 
OK or  not OK ?  or wrong folder  ??
[](url)
![folder](https://github.com/PHARTGAMES/SpaceMonkey/assets/148687193/82bc9ffc-c908-4467-a258-98366508f013)

**Comment by PHARTGAMES** [comment]
Yeah sorry it's not entirely clear, an installer would be ideal for this

you copy paste those Content and Binaries folders into the Dakar2Game folder so that Dakar2Game looks like this

![image](https://github.com/PHARTGAMES/SpaceMonkey/assets/13314042/d10f1a56-7b5c-4385-bec1-d291adfee850)

**Comment by Siethof** [comment]
Thankx,

Will try this evening!

Op wo 25 okt. 2023 om 02:35 schreef PHARTGAMES ***@***.***>

**Comment by Siethof** [comment]
Working now. Thankx👍

Have to extract and then kopie binaries and content file. Those files are
already there, but it replaces some(8) files with same name.
Dont know how to explain this on easy way in manual.!
Understand how how it should work now.
Anyway dakar is a lot of fun with motion jumping over the dunes👍
Power plug came out the display when jumping 😀😀👍


Op wo 25 okt. 2023 om 02:35 schreef PHARTGAMES ***@***.***>

**Comment by PHARTGAMES** [comment]
Lol great!
